#!/bin/bash
# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x5"
#BLURTYPE="0x2"
BLURTYPE="5x5"
#BLURTYPE="2x8"
#BLURTYPE="2x3"

i3lock -i /home/dani/.config/i3/i3lock/text.png
